spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  rabbitmq:
    host: 192.168.246.130
    port: 5672
    username: admin
    password: 123456
#    开启后,消息发布到交换机后会触发回调函数
    publisher-confirm-type: correlated
#    开启后,投递或路由失败的的消息将会回退给生产者
    publisher-returns: true